# Generated by Django 5.2.14 on 2026-05-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zone_type', models.CharField(choices=[('STORAGE', '보관 구역'), ('CHARGING', '충전 구역'), ('WORK_AREA', '작업 구역'), ('STAGING', '대기 구역')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IDLE', '대기'), ('BUSY', '작업 중'), ('CHARGING', '충전 중'), ('ERROR', '오류')], default='IDLE', max_length=20)),
                ('battery_level', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to='robots.zone')),
            ],
            options={
                'db_table': 'robot',
            },
        ),
    ]
