# Generated by Django 5.2.14 on 2026-05-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('ASSIGNED', '배정됨'), ('IN_PROGRESS', '진행 중'), ('DONE', '완료'), ('TIMEOUT', '타임아웃')], default='PENDING', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_from', to='robots.zone')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='robots.robot')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_to', to='robots.zone')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='tasks.task')),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
